
CREATE TABLE DBO.LOG_PROCESOS(
	ID_PROCESO			BIGINT NOT NULL IDENTITY(1,1),
	PROCESO				VARCHAR(100),
	COMANDO				VARCHAR(1000),
	ESTADO				VARCHAR(100),
	ERROR_DESCRIPCION	VARCHAR(4000),
	FECHA_EJECUCION		DATETIME,
	REF_1				VARCHAR(1000),
	REF_2				VARCHAR(1000),
	REF_DATE_1			DATETIME,
);
GO

ALTER TABLE DBO.LOG_PROCESOS ADD CONSTRAINT CHK_PROCESOS_ESTADO CHECK (ESTADO IN('OK','ERR'))