/****** Object:  StoredProcedure [dbo].[INS_LOG_PROCESO]    Script Date: 03/10/2016 12:29:31 p. m. ******/
DROP PROCEDURE [dbo].[INS_LOG_PROCESO]
GO

CREATE PROCEDURE [dbo].[INS_LOG_PROCESO]
@DOCUMENTO_REF		VARCHAR(100),
@NRO_LINEA_REF		NUMERIC(10,0),
@PROCESO			VARCHAR(100),
@COMANDO			VARCHAR(1000),
@ESTADO				VARCHAR(100),
@OBS_PROCESO		VARCHAR(4000),
@REF_1				VARCHAR(1000),
@REF_2				VARCHAR(1000),
@REF_DATE_1			DATETIME
AS
BEGIN

	INSERT INTO LOG_PROCESOS (DOCUMENTO_REF, NRO_LINEA_REF, PROCESO, COMANDO, ESTADO, OBS_PROCESO, FECHA_EJECUCION, REF_1, REF_2, REF_DATE_1)
	VALUES (@DOCUMENTO_REF, @NRO_LINEA_REF, @PROCESO, @COMANDO, @ESTADO,@OBS_PROCESO, GETDATE(), @REF_1, @REF_2, @REF_DATE_1)

END
GO


