--SELECT * FROM LOG_PROCESOS
BEGIN TRY
	DROP PROCEDURE DBO.INS_LOG_PROCESO
END TRY BEGIN CATCH END CATCH
GO

CREATE PROCEDURE DBO.INS_LOG_PROCESO
@PROCESO			VARCHAR(100),
@COMANDO			VARCHAR(1000),
@ESTADO				VARCHAR(100),
@ERROR_DESCRIPCION	VARCHAR(4000),
@REF_1				VARCHAR(1000),
@REF_2				VARCHAR(1000)
AS
BEGIN

	INSERT INTO LOG_PROCESOS (PROCESO, COMANDO, ESTADO, ERROR_DESCRIPCION, FECHA_EJECUCION, REF_1, REF_2)
	VALUES (@PROCESO, @COMANDO, @ESTADO,@ERROR_DESCRIPCION, GETDATE(), @REF_1, @REF_2)

END